language: node_js
sudo: true
dist: trusty
node_js:
  - 10
branches:
  except:
    - /^v[0-9]/
install:
  - yarn install --pure-lockfile
  - npm install -g codecov
script:
  - yarn packages:bundle
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
cache:
  directories:
    - '$HOME/.yarn-cache'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
